sudo: false
language: elixir
elixir:
  - 1.6.3
  - 1.7.2
otp_release:
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.6.3
      otp_release: 21.0
env:
  - MIX_ENV=test
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hashdeep
script:
  - bash scripts/verify_generated_erlang_code.sh
  - mix test --trace
  - bash scripts/integration_test.sh
  - if [[ "$TRAVIS_ELIXIR_VERSION" == "1.7.2" ]]; then mix format --check-formatted; else echo "not checking formatting for elixir 1.6"; fi
  - mix dialyzer --halt-exit-status
cache:
  directories:
    - _build
before_cache:
  # should only keep the dialyzer artifacts
  - mix clean
  - mix deps.clean --all

