sudo: false
language: elixir
elixir:
  - 1.6.3
  - 1.7.2
otp_release:
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.6.3
      otp_release: 21.0
env:
  - MIX_ENV=test
script:
  - mix test --trace
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
cache:
  directories:
    - _build
before_cache:
  # should only keep the dialyzer artifacts
  - mix clean
  - mix deps.clean --all

